"""add_prize_pool_description_to_tournament

Revision ID: 0f0ba00e6afc
Revises: clear_old_users
Create Date: 2025-11-21 21:34:31.878969

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0f0ba00e6afc'
down_revision: Union[str, None] = 'clear_old_users'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_bitcoin_candles_close_time', table_name='bitcoin_candles')
    op.drop_index('ix_bitcoin_candles_id', table_name='bitcoin_candles')
    op.drop_index('ix_bitcoin_candles_interval', table_name='bitcoin_candles')
    op.drop_index('ix_bitcoin_candles_open_time', table_name='bitcoin_candles')
    op.drop_index('ix_bitcoin_candles_symbol', table_name='bitcoin_candles')
    op.drop_table('bitcoin_candles')
    op.add_column('tournaments', sa.Column('description', sa.String(), nullable=True))
    op.add_column('tournaments', sa.Column('prize_pool', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tournaments', 'prize_pool')
    op.drop_column('tournaments', 'description')
    op.create_table('bitcoin_candles',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('symbol', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('interval', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('open_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('close_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('open_price', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('high_price', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('low_price', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('close_price', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('volume', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('quote_asset_volume', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('number_of_trades', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('taker_buy_base_volume', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('taker_buy_quote_volume', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='bitcoin_candles_pkey'),
    sa.UniqueConstraint('symbol', 'interval', 'open_time', name='unique_candle')
    )
    op.create_index('ix_bitcoin_candles_symbol', 'bitcoin_candles', ['symbol'], unique=False)
    op.create_index('ix_bitcoin_candles_open_time', 'bitcoin_candles', ['open_time'], unique=False)
    op.create_index('ix_bitcoin_candles_interval', 'bitcoin_candles', ['interval'], unique=False)
    op.create_index('ix_bitcoin_candles_id', 'bitcoin_candles', ['id'], unique=False)
    op.create_index('ix_bitcoin_candles_close_time', 'bitcoin_candles', ['close_time'], unique=False)
    # ### end Alembic commands ###
