"""add_demo_wallet_and_demo_order_tables

Revision ID: 95d742b5d862
Revises: 0f0ba00e6afc
Create Date: 2025-11-22 00:20:46.406601

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '95d742b5d862'
down_revision: Union[str, None] = '0f0ba00e6afc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('demo_orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('symbol', sa.String(), nullable=True),
    sa.Column('side', sa.String(), nullable=True),
    sa.Column('size', sa.Float(), nullable=True),
    sa.Column('entry_price', sa.Float(), nullable=True),
    sa.Column('current_price', sa.Float(), nullable=True),
    sa.Column('stop_loss', sa.Float(), nullable=True),
    sa.Column('take_profit', sa.Float(), nullable=True),
    sa.Column('pnl', sa.Float(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('close_price', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('closed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_demo_orders_created_at'), 'demo_orders', ['created_at'], unique=False)
    op.create_index(op.f('ix_demo_orders_id'), 'demo_orders', ['id'], unique=False)
    op.create_index(op.f('ix_demo_orders_symbol'), 'demo_orders', ['symbol'], unique=False)
    op.create_index(op.f('ix_demo_orders_user_id'), 'demo_orders', ['user_id'], unique=False)
    op.create_table('demo_wallets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('balance', sa.Float(), nullable=True),
    sa.Column('currency', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_demo_wallets_id'), 'demo_wallets', ['id'], unique=False)
    op.create_index(op.f('ix_demo_wallets_user_id'), 'demo_wallets', ['user_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_demo_wallets_user_id'), table_name='demo_wallets')
    op.drop_index(op.f('ix_demo_wallets_id'), table_name='demo_wallets')
    op.drop_table('demo_wallets')
    op.drop_index(op.f('ix_demo_orders_user_id'), table_name='demo_orders')
    op.drop_index(op.f('ix_demo_orders_symbol'), table_name='demo_orders')
    op.drop_index(op.f('ix_demo_orders_id'), table_name='demo_orders')
    op.drop_index(op.f('ix_demo_orders_created_at'), table_name='demo_orders')
    op.drop_table('demo_orders')
    # ### end Alembic commands ###
